sudo: false

dist: trusty

language: php

cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

env:
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1

php:
  - nightly
  - 7.2
  - 7.1.12
  - 7.1
  - 7.0.26
  - 7.0
  - 5.6.32
  - 5.6
  - 5.5.38
  - 5.5
  - 5.4.45
  - 5.4

services:
  - mysql

addons:
  - mariadb: '5.5'
  - mariadb: '10.0'

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;

notifications:
email: false
